version: '3.9'

services:

  golang:
    image: golang:1.22
    working_dir: /go/src/my_project
    volumes:
      - .:/go/src/my_project
    command: go run main.go
    ports:
      - 8080:8080
    depends_on:
      - db
    environment:
      - DB_PASSWORD=qwerty

  db:
    restart: always
    image: postgres:latest
    volumes:
      - ./.database/postgres/data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=qwerty
    ports:
      - 5436:5432